# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.define "server" do |server|
        server.vm.box = "shekeriev/centos-stream-8"
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "192.168.99.101"
        server.vm.provision "shell", path: "add_hosts.sh"
        server.vm.provision "shell", path: "install_elasticstack.sh"
        server.vm.provision "shell", path: "conf_logstash.sh"
        server.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 8192
            v.cpus = 2
        end
    end
  
    config.vm.define "node1" do |node1|
        node1.vm.box = "shekeriev/centos-stream-8"
        node1.vm.hostname = "node1"
        node1.vm.network "private_network", ip: "192.168.99.102"
        node1.vm.provision "shell", path: "add_hosts.sh"
        node1.vm.provision "shell", path: "install_metricbeat_centos.sh"
        node1.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end
  
    config.vm.define "node2" do |node2|
        node2.vm.box = "shekeriev/debian-11"
        node2.vm.hostname = "node2"
        node2.vm.network "private_network", ip: "192.168.99.103"
        node2.vm.provision "shell", path: "add_hosts.sh"
        node2.vm.provision "shell", path: "install_metricbeat_deb.sh"
        node2.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
            v.customize ["modifyvm", :id, "--usb", "on"]
            v.customize ["modifyvm", :id, "--usbehci", "off"]
        end
    end

end
