global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'pipelines'
    static_configs:
    - targets: ['pipelines:9100']
  - job_name: 'containers'
    static_configs:
    - targets: ['containers:9100']
