# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.define "pipelines" do |pipelines|
        pipelines.vm.box = "shekeriev/centos-stream-8"
        pipelines.vm.hostname = "pipelines.do1.exam"
        pipelines.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "3072"]
        end
        pipelines.vm.network "private_network", ip: "192.168.111.201"
        pipelines.vm.network "forwarded_port", guest: 8080, host: 8080
        pipelines.vm.provision "shell", path: "add_hosts.sh"
        pipelines.vm.provision "shell", path: "install_jenkins.sh"
        pipelines.vm.provision "shell", path: "install_node_exporter.sh"
    end
  
    config.vm.define "containers" do |containers|
        containers.vm.box = "shekeriev/centos-stream-8"
        containers.vm.hostname = "containers.do1.exam"
        containers.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "3072"]
        end
        containers.vm.network "private_network", ip: "192.168.111.202"
        containers.vm.network "forwarded_port", guest: 8080, host: 8081
        containers.vm.provision "shell", path: "add_hosts.sh"
        containers.vm.provision "shell", path: "install_docker.sh"
        containers.vm.provision "shell", path: "run_gitea.sh"
        containers.vm.provision "shell", path: "install_node_exporter.sh"
    end
  
    config.vm.define "monitoring" do |monitoring|
        monitoring.vm.box = "shekeriev/centos-stream-8"
        monitoring.vm.hostname = "monitoring.do1.exam"
        monitoring.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "3072"]
        end
        monitoring.vm.network "private_network", ip: "192.168.111.203"
        monitoring.vm.network "forwarded_port", guest: 9090, host: 8082
        monitoring.vm.network "forwarded_port", guest: 3000, host: 8083
        monitoring.vm.provision "shell", path: "add_hosts.sh"
        monitoring.vm.provision "shell", path: "install_promgraf.sh"
    end

end
