# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.ssh.insert_key = false

    config.vm.define "jdocker" do |jdocker|
        jdocker.vm.box = "shekeriev/centos-stream-8"
        jdocker.vm.hostname = "jdocker.do1.lab"
        jdocker.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "3072"]
        end
        jdocker.vm.network "private_network", ip: "192.168.99.100"
        jdocker.vm.network "forwarded_port", guest: 80, host: 8000
        jdocker.vm.network "forwarded_port", guest: 8080, host: 8080
        jdocker.vm.provision "shell", path: "jdocker_setup.sh"
    end

end
