# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "M1-HW-Ubuntu-Server"
    config.ssh.forward_agent = true
    config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y git apache2 curl mysql-server php libapache2-mod-php php-mysql
        sudo systemctl restart apache2
        sudo ufw default deny incoming
        sudo ufw default allow outgoing
        sudo ufw allow ssh    
        sudo systemctl stop apparmor.service
        sudo systemctl disable apparmor.service
        git clone https://github.com/shekeriev/dob-module-1
        sudo rm /var/www/html/index.html
        sudo cp dob-module-1/web/* /var/www/html/
        mysql -u root < /home/vagrant/dob-module-1/db/db_setup.sql
    SHELL
end
